ALTER TABLE fos_identity.actor
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE fos_canonical.player
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE fos_canonical.team
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
